### ISSUE TITLE
Axis example component squishes numTicks on change

### ISSUE THREAD

**Issue by abmagil** [coreyflynn/jubilation#17]
![squishy numticks](https://cloud.githubusercontent.com/assets/2807766/21699503/03dc743a-d36a-11e6-884b-c8252c02b629.gif)

On the examples page, editing the "numTicks" field for either axis works, except on re-render, the ticks are all squished under the 100 mark, instead of being spread out.

**Comment by coreyflynn** [comment]
I think we solved this bad boy. @abmagil can you confirm?

**Comment by abmagil** [comment]
Yup. Forgot to link the pr to the issue, but that's the one!
