### ISSUE TITLE
Create line component

### ISSUE THREAD

**Issue by coreyflynn** [coreyflynn/jubilation#4]
should be a stateless component that takes `x1`, `y1`, `x2`, `y2` in as props and renders an SVG line element with any additional props set on the output line.
- [x] The line should use `xScale` and `yScale` from the passed in context or the default context if one is not given
- [x] The line should default its stroke to the `theme.labelStyle.fill` color taken from either a passed in `JubilationContext` or the default context if one is not given
- [x] The line should be wrapped in an `Animation` component.

See https://github.com/coreyflynn/jubilation/blob/master/src/jubilation-point/index.jsx for a similar component that implements an SVG circle.
See the SVG line docs at https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line for reference.

**Comment by abmagil** [comment]
Implemented by #9
