### ISSUE TITLE
Enable tick lines for X and Y axes

### ISSUE THREAD

**Issue by coreyflynn** [coreyflynn/jubilation#5]
- should be controlled through the `tickLines` prop passed to axis components
- should span the whole width or height of the graph (computed from `xScale` and `yScale` from context, respectively)
- should be drawn with a `Line` component built (see #4)

**Comment by abmagil** [comment]
@coreyflynn any opinions on default behavior?  I'm thinking that since the axis defaults to labeling at start-midpoint-end, the ticks should go there.

**Comment by coreyflynn** [comment]
we should just render a tickline wherever we compute the axis labels to be

**Comment by abmagil** [comment]
@coreyflynn what's the difference between `numTicks = 0` and `tickLines = false`?

**Comment by abmagil** [comment]
Also, aren't these minor axes?  If they span the whole graph?

**Comment by coreyflynn** [comment]
@abmagil `numTicks` is meant to control the number of ticks shown on the axis. `TickLines` is meant to control if those line are extended across the graph perpendicular to the axis being drawn. Maybe better to call them `gridLines`?

here, the ticks are drawn in red and the `tickLines/gridLines` are drawn in green
![tmp](https://cloud.githubusercontent.com/assets/408448/21077822/3bc0084c-bf26-11e6-8222-c0e2e19bdd62.png)

the goal is to turn the green lines off and on if we want to
